name: CI and CD

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./presentation
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: npm install        
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run-script build
        working-directory: ${{env.working-directory}}
      - name: Install Surge
        run: npm install --global surge
      - name: Add CNAME
        run: echo wer-rusted-der-rosted-nicht.surge.sh > ./public/CNAME
      - name: Publish
        run: surge ./public/
