name: CI and CD

on:
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: "10.x"
      - run: npm install
      - run: npm run-script build
